### ISSUE TITLE
`GLIBC_2.33' not found

### ISSUE THREAD

**Issue by ransome1** [KSXGitHub/github-actions-deploy-aur#14]
Hi @KSXGitHub.

I'm trying to publish my PKGBUILD to AUR using the action you created.

Unfortunately Github CI is aborting the job stating:
```
Run KSXGitHub/github-actions-deploy-aur@v2
  with:
    pkgname: sleek
    pkgbuild: ./PKGBUILD
    commit_username: ***
    commit_email: ***
    ssh_private_key: ***
    commit_message: Update to latest sleek release
    ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
/usr/bin/docker run --name e409800e00edda48ba857a1a2263fe1ec2_4928f2 --label 5588e4 --workdir /github/workspace --rm -e INPUT_PKGNAME -e INPUT_PKGBUILD -e INPUT_COMMIT_USERNAME -e INPUT_COMMIT_EMAIL -e INPUT_SSH_PRIVATE_KEY -e INPUT_COMMIT_MESSAGE -e INPUT_SSH_KEYSCAN_TYPES -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/sleek/sleek":"/github/workspace" 5588e4:09800e00edda48ba857a1a2263fe1ec2
Creating builder user...
passwd: password expiry information changed.
Initializing ssh directory...
mkdir: created directory '/home/builder/.ssh'
'/ssh_config' -> '/home/builder/.ssh/config'
ownership of '/home/builder/.bash_logout' retained as builder:builder
changed ownership of '/home/builder/.ssh/known_hosts' from root:root to builder:builder
changed ownership of '/home/builder/.ssh/config' from root:root to builder:builder
changed ownership of '/home/builder/.ssh' from root:root to builder:builder
ownership of '/home/builder/.bash_profile' retained as builder:builder
ownership of '/home/builder/.bashrc' retained as builder:builder
ownership of '/home/builder' retained as builder:builder
mode of '/home/builder/.ssh/config' changed from 0644 (rw-r--r--) to 0600 (rw-------)
mode of '/home/builder/.ssh/known_hosts' changed from 0644 (rw-r--r--) to 0600 (rw-------)
Copying PKGBUILD...
Running build.sh...
runuser: /usr/lib/libc.so.6: version `GLIBC_2.33' not found (required by runuser)
``` 

Do you have any idea how I could solve this?

This is the job's part in my yml:
```
  publish-aur-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2
        with:
          pkgname: sleek
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update to latest sleek release
```
Best
