### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SquitchYT** [KSXGitHub/github-actions-deploy-aur#18]
Hello, I have an error :
```
error: src refspec master does not match any
error: failed to push some refs to 'ssh://aur.archlinux.org/tess-git.git'
```

**Comment by KSXGitHub** [comment]
Can you give me more context? Such as your workflow file, full error messages, etc.

**Comment by SquitchYT** [comment]
Hello, thanks you for the response.
that is my workflow file : 
```
jobs: 
    pkgbuild: 
        runs-on: ubuntu-latest 
        steps: 
          - uses: actions/checkout@v2 
          
          - name: Update PKGBUILD 
            uses: 2m/arch-pkgbuild-builder@v1.16 
            with: 
              target: 'pkgbuild' 
              pkgname: 'tess-git' 
          - name: Publish AUR package 
            uses: KSXGitHub/github-actions-deploy-aur@v2.2.5 
            with: 
              pkgname: tess-git 
              pkgbuild: tess-git/PKGBUILD 
              commit_username: ${{ secrets.AUR_USERNAME }} 
              commit_email: ${{ secrets.AUR_EMAIL }} 
              ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }} 
              commit_message: Update AUR package 
              ssh_keyscan_types: rsa
```

All log : 
```
Cloning into '/tmp/local-repo'...
  POST git-upload-pack (227 bytes)
  Note: switching to 'b736e7703e93fa8613db3be372a9fc92ef9a0d5b'.
  
  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by switching back to a branch.
  
  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -c with the switch command. Example:
  
    git switch -c <new-branch-name>
  
  Or undo this operation with:
  
    git switch -
  
  Turn off this advice by setting config variable advice.detachedHead to false

Copying PKGBUILD...
  '/PKGBUILD' -> './PKGBUILD'
  Updating .SRCINFO

add '.SRCINFO'
  add 'PKGBUILD'
  [detached HEAD d9cb073] Update AUR package
   2 files changed, 2 insertions(+), 2 deletions(-)
  Pushing to ssh://aur.archlinux.org/tess-git.git
  error: src refspec master does not match any
  error: failed to push some refs to 'ssh://aur.archlinux.org/tess-git.git'

```
